### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by dloscutoff** [dloscutoff/pip#27]
Complex numbers could be implemented as another way of interpreting a Scalar numerically: before checking if a prefix of the string looks like a float or an int, check for a prefix that looks like `(number)+/-(number)j` or `(number)j`. Do whatever operation needs to be done on the value using the Python `complex` type, and cast any `complex` result back to a Scalar before returning.

(Technically, this would break backwards compatibility, since right now `2 * "3+4j"` returns `6` rather than `"6+8j"`--though I don't recall ever having written a program where that change would make a difference.)

Some questions: Do we interpret a string like `"1-j"` as a complex number? What about `"-j"`, or just `"j"`? What about `"5jumpingjacks"`? Do we use `j` as a variable preinitialized to the complex unit, or as part of imaginary-number literals like in Python? How should we write the repr of complex numbers?

**Comment by dloscutoff** [comment]
There is an absurd amount of space for adding two-byte primitives: any pair of uppercase letters parses as a token, which gives 676 combinations; 92 are currently in use as operators, 19 as variables, and 2 as commands, leaving 563 available. But I'm also still on the fence about adding complex numbers, since it would be a lot of work to update everything that takes a number to handle a possibly complex argument.

**Comment by razetime** [comment]
Adding more two byte primitives lessens the effectiveness of single byte primitives when they're used, quite often. But it's good to know there is space.

**Comment by dloscutoff** [comment]
I've decided not to bother with complex numbers, at least not as part of the core number system. It would add too much complexity (heh) for not enough benefit.
