### ISSUE TITLE
Empty program handled incorrectly

### ISSUE THREAD

**Issue by dloscutoff** [dloscutoff/pip#51]
Running an empty program (for example, `pip.py -e ""`) should trivially succeed and do nothing. However, currently, it prints a usage message and exits.

The cause appears to be some lines in `pip.py` that check the truthiness of `code` when they should check `code is not None`.

**Comment by AviFS** [comment]
There's only one instance of `sys.exit(0)` and it's on line 154 of pip.py. Looks to me like changing that line to `return` does the trick! I don't know how to run any tests you might have, but I can make a PR real quick.

**Comment by dloscutoff** [comment]
Nope, that's supposed to be there--it prints that usage message if someone tries to run something like `pip.py -p` where they don't seem to want interactive mode but also haven't specified where the code is coming from. The problem is that that line should only be reached if `code` is `None`, but due to my short-sighted conditionals, it's also reached under certain circumstances if `code` is `""`.
